version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: blog
    container_name: blog
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - blog

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql.cnf:/etc/mysql/my.cnf
    networks:
      - blog

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - blog
      - traefik-global-proxy
    # Labels for traefik
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.network=traefik-global-proxy"
      - "traefik.http.routers.nginx.rule=Host(`$DOMAIN`) || Host(`www.$DOMAIN`)"
      - "traefik.http.middlewares.test-redirectregex.redirectregex.regex=^https://www.(.*)"
      - "traefik.http.middlewares.test-redirectregex.redirectregex.replacement=https://$${1}"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=le"
      - "traefik.http.middlewares.nginx_gzip_compress.compress=true"
      - "traefik.http.routers.nginx.middlewares=nginx_gzip_compress"

networks:
  traefik-global-proxy:
    external: true
  blog:
    driver: bridge
volumes:
  dbdata:
    driver: local
