# For more information: https://laravel.com/docs/sail
version: "3"
networks:
  web:
    external: true # traefik reverse proxy
  internal:
    external: false
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./php-prod.ini:/usr/local/etc/php/conf.d/local.ini
    image: website
    container_name: website
    restart: unless-stopped
    working_dir: /var/www/
    networks:
      - internal
    labels:
      - "traefik.enable=false"
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql.prod.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - internal
    labels:
      - "traefik.enable=false"
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - web
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`andreafalcon.dev`)"
      - "traefik.http.routers.website.entrypoints=websecure"
      - "traefik.docker.network=web"
      - "traefik.http.routers.website.tls.certresolver=le"
volumes:
  dbdata:
    driver: local
